"""Slice STLs into gcode with the PrusaSlicer command line.

One printer, one filament, one profile: `slicer/profile.ini`, captured from a
print that came out well. See docs/adr/0003-slice-in-repo-with-prusaslicer-cli.md.
"""

import os
import re
import shutil
import subprocess
from pathlib import Path

from .build import REPO
from .motif import Motif

PROFILE = REPO / "slicer" / "profile.ini"

_TIMESTAMP = re.compile(r"^(; generated by PrusaSlicer \S+) on .*$", re.MULTILINE)


class SlicerMissing(Exception):
    pass


def slicer_binary() -> str:
    """Path to prusa-slicer. Set PRUSA_SLICER to point at a different binary."""
    candidate = os.environ.get("PRUSA_SLICER", "prusa-slicer")
    found = shutil.which(candidate)
    if found is None:
        raise SlicerMissing(
            f"cannot find {candidate!r}. Install PrusaSlicer (apt install prusa-slicer) "
            "or set PRUSA_SLICER to its path."
        )
    return found


def slice_stl(stl: Path, gcode: Path, profile: Path = PROFILE) -> None:
    """Slice one STL to gcode, then make the file byte-for-byte reproducible.

    PrusaSlicer writes the current time into the first line. Everything else is
    deterministic for a given slicer version, profile, and STL, so that one line is
    trimmed to keep the committed gcode stable across rebuilds.
    """
    gcode.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            slicer_binary(),
            "--export-gcode",
            "--load",
            str(profile),
            "--output",
            str(gcode),
            str(stl),
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
    )
    text = gcode.read_text()
    gcode.write_text(_TIMESTAMP.sub(r"\1", text, count=1))


def slice_motif(motif: Motif, out: Path = REPO) -> Path:
    """Slice the motif's built STL under `out` into `out/gcode/<name>.gcode`."""
    stl = out / "stl" / f"{motif.name}.stl"
    if not stl.exists():
        raise FileNotFoundError(f"{stl} is missing. Run `dominoez build {motif.name}` first.")
    gcode = out / "gcode" / f"{motif.name}.gcode"
    slice_stl(stl, gcode)
    return gcode


def stats(gcode: Path) -> dict[str, str]:
    """The slicer's summary lines (filament used, estimated time) as a dict."""
    found = {}
    for line in gcode.read_text().splitlines():
        if line.startswith("; ") and " = " in line and not line.startswith("; prusaslicer"):
            key, _, value = line[2:].partition(" = ")
            if key.startswith(("filament used", "estimated printing time", "total filament used")):
                found[key] = value
    return found
