import hashlib
import shutil

import pytest

from dominoez.build import build_motif
from dominoez.motifs import MOTIFS
from dominoez.slice import PROFILE, slice_motif, stats

needs_slicer = pytest.mark.skipif(
    shutil.which("prusa-slicer") is None, reason="prusa-slicer is not installed"
)


def _profile() -> dict[str, str]:
    values = {}
    for line in PROFILE.read_text().splitlines():
        if line and not line.startswith("#"):
            key, _, value = line.partition(" = ")
            values[key] = value
    return values


def test_profile_matches_the_guidelines():
    p = _profile()
    assert p["nozzle_diameter"] == "0.4"
    assert p["layer_height"] == "0.2"
    assert p["perimeters"] == "3"
    assert p["fill_density"] == "10%"
    assert p["fill_pattern"] == "grid"
    assert p["support_material"] == "0"
    assert p["printer_model"] == "CR10SMARTPRO"
    assert p["filament_type"] == "PLA"


@needs_slicer
def test_blank_slices_and_is_deterministic(tmp_path):
    hashes = []
    for name in ("a", "b"):
        out = tmp_path / name
        out.mkdir()
        build_motif(MOTIFS["blank"], out)
        gcode = slice_motif(MOTIFS["blank"], out)
        text = gcode.read_text()
        assert text.startswith("; generated by PrusaSlicer ")
        assert " on " not in text.splitlines()[0], "timestamp should be stripped"
        assert "G28" in text and "M104" in text
        summary = stats(gcode)
        grams = float(summary["filament used [g]"])
        assert 10 < grams < 20, summary
        hashes.append(hashlib.sha256(text.encode()).hexdigest())
    assert hashes[0] == hashes[1]


def test_slice_needs_a_built_stl(tmp_path):
    with pytest.raises(FileNotFoundError):
        slice_motif(MOTIFS["blank"], tmp_path)
